# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
# Download the pgp keys from azure secure library
- task: DownloadSecureFile@1
  displayName: 'Get secring.asc from Azure Secure Library'
  inputs:
    secureFile: "secring.asc"

- task: DownloadSecureFile@1
  displayName: 'Get pubring.asc from Azure Secure Library'
  inputs:
    secureFile: "pubring.asc"    

- script: |
    mkdir -p /tmp/pgp && \
    mv $(DownloadSecureFile1.secureFilePath) /tmp/pgp && \
    mv $(DownloadSecureFile2.secureFilePath) /tmp/pgp
  displayName: 'Move pgp keys'  

- script: |
    docker run \
    -d \
    --name sbt \
    -v $(pwd):/app \
    -v /tmp/pgp:/pgp \
    mozilla/sbt:8u212_1.2.8 \
    tail -f /dev/null
  displayName: 'Create a docker based testing environment (including mozilla/sbt:8u212_1.2.8)'

- script: |
    docker exec \
    -w /app \
    sbt \
    sbt test
  displayName: 'sbt test'

- script: |
    docker exec \
    -e SONATYPE_USERNAME=$(SONATYPE_USERNAME) \
    -e SONATYPE_PASSWORD=$(SONATYPE_PASSWORD) \
    -e PGP_PASSPHRASE=$(PGP_PASSPHRASE) \
    -w /app \
    sbt \
    sbt publishSigned
  displayName: 'sbt publishSigned (push to https://oss.sonatype.org/content/groups/staging/)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
