---
version: '3.5'

networks:
  arc-integration:
    name: arc-integration
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/24

services:
  sbt:
    container_name: sbt
    image: amazoncorretto:8
    networks:
      - arc-integration
    command: tail -F anything
    volumes:
      - ${PWD}:/app
      - /tmp/pgp:/pgp
    working_dir: /app